#!/bin/sh

PREREQ=""

prereqs()
{
    echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions



DISABLE_ROOT_RO=
for CMD_PARAM in $(cat /proc/cmdline); do
    case ${CMD_PARAM} in
        disable-root-ro=*)
            DISABLE_ROOT_RO=${CMD_PARAM#disable-root-ro=}
            ;;
    esac
done

if [ ! -z "${DISABLE_ROOT_RO}" ]; then
    log_warning_msg "root-ro: disabled, found boot parameter disable-root-ro=${DISABLE_ROOT_RO}"
    exit 0
fi



mkdir -p /mnt/ramdisk
mkdir -p /mnt/root-ro
mount -t tmpfs -o size=256m tmpfs /mnt/ramdisk
mkdir -p /mnt/ramdisk/root-rw
mkdir -p /mnt/ramdisk/overlay-work

mount --move ${rootmnt} /mnt/root-ro
mount -t overlay overlay -o lowerdir=/mnt/root-ro,upperdir=/mnt/ramdisk/root-rw,workdir=/mnt/ramdisk/overlay-work ${rootmnt}

mkdir -p ${rootmnt}/mnt/root-ro
mkdir -p ${rootmnt}/mnt/ramdisk

# Move mounts
mount --move /mnt/root-ro ${rootmnt}/mnt/root-ro
mount --move /mnt/ramdisk ${rootmnt}/mnt/ramdisk


log_success_msg "root-ro sucessfully set up ro/tmpfs-rw layered root fs"

exit 0